### ISSUE TITLE
The /var/task/user/bootstrap/cache directory must be present and writable.

### ISSUE THREAD

**Issue by adrian-ub** [calebporzio/vercel-laravel#3]
Hello, I have followed this tutorial to try to implement my blog in vercel, but wanting to do a nested components it shows me the error described.

```
The /var/task/user/bootstrap/cache directory must be present and writable. (View: /var/task/user/resources/views/livewire/welcome.blade.php) (View: /var/task/user/resources/views/livewire/welcome.blade.php)

```

[adrianub-1w14w1gbg.vercel.app](adrianub-1w14w1gbg.vercel.app)

**Comment by 1isten** [comment]
Hi @adrian-ub did you fix this problem?
